# Generated by Django 4.2.7 on 2023-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0002_vehicle_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
