# Generated by Django 4.2.7 on 2023-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0008_alter_moreinfo_body_type_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='body_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Compact'), (3, 'Truck'), (0, 'Other'), (5, 'Coupe'), (1, 'Sedan'), (2, 'Wagon')], default=0),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_designation', models.CharField(max_length=23)),
                ('cars', models.ManyToManyField(to='carweb.vehicle')),
            ],
        ),
    ]
