# Generated by Django 4.2.7 on 2023-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0003_vehicle_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_specification',
            field=models.TextField(default=' no description '),
        ),
    ]
