# Generated by Django 4.2.7 on 2023-11-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0004_vehicle_car_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='production_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='production_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
