# Generated by Django 4.2.7 on 2023-12-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0007_moreinfo_vehicle_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='body_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Wagon'), (0, 'Other'), (5, 'Coupe'), (3, 'Truck'), (4, 'Compact'), (1, 'Sedan')], default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(blank=True, default='')),
                ('coolness_rating', models.PositiveSmallIntegerField(default=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carweb.vehicle')),
            ],
        ),
    ]
