# Generated by Django 4.2.7 on 2023-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0009_alter_moreinfo_body_type_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='body_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Wagon'), (4, 'Compact'), (3, 'Truck'), (1, 'Sedan'), (5, 'Coupe'), (0, 'Other')], default=0),
        ),
    ]
